@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Jun 26 01:16:06 +0300 2025
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto ea78da8c92fe4f1fbd995d29f620c0d6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_capture_to_buffer_behav xil_defaultlib.tb_capture_to_buffer -log elaborate.log"
call xelab  -wto ea78da8c92fe4f1fbd995d29f620c0d6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_capture_to_buffer_behav xil_defaultlib.tb_capture_to_buffer -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
